apiVersion: v2
name: openshift-logging
description: Deploy and configure OpenShift Logging including Elasticsearch and Kibana
version: 1.0.28
home: https://github.com/luisbazo/helm-charts/tree/main/charts/openshift-logging
dependencies:
  - name: helper-operator
    version: ~1.0.18
    repository: https://charts.stderr.at/
  - name: helper-status-checker
    version: ~4.0.0
    repository: https://charts.stderr.at/
    condition: helper-status-checker.enabled
  - name: helper-lokistack
    version: ~1.0.1
    repository: https://charts.stderr.at/
  - name: helper-objectstore
    version: ~1.0.4
    repository: https://charts.stderr.at/
  - name: helper-loki-bucket-secret
    version: ~1.0.6
    repository: https://charts.stderr.at/
maintainers:
  - name: luisbazo
    email: luis.bazo@gmail.com
    url: https://blog.stderr.at/
sources:
  - https://github.com/tjungbauer/helm-charts
  - https://charts.stderr.at/
  - https://github.com/tjungbauer/openshift-clusterconfig-gitops
keywords:
  - logging
