---
loggingConfig:
  enabled: true
  syncwave: '4'
  # Indicator if the resource is 'Managed' or 'Unmanaged' by the operator
  # managementState: Managed
  # Specification of the Log Storage component for the cluster
  logStore:
    # The Type of Log Storage to configure. The operator currently supports either using ElasticSearch managed by elasticsearch-operator or Loki managed by loki-operator (LokiStack) as a default log store.
    type: lokistack
    # Name of the LokiStack resource.
    lokistack: logging-loki
    retentionPolicy:
      application:
        maxAge: 1d
      audit:
        maxAge: 1d
      infra:
        maxAge: 1d
    visualization:
      # The type of Visualization to configure
      # Could be either Kibana or ocp-console
      type: ocp-console
    collection:
      # The type of Log Collection to configure
      # Vector in case of Loki...
      type: vector
      # The resource requirements for the collector
      # resources:
      #   limits:
      #     cpu: '500m'
      #     memory: '1Gi'
      #     ephemeral-storage: '50Mi'
      #   requests:
      #     cpu: '500m'
      #     memory: '1Gi'
      #     ephemeral-storage: '500Mi'
      # Define the tolerations the Pods will accept
      # tolerations:
      #  - effect: NoSchedule
      #    key: infra
      #    operator: Equal
      #    value: 'reserved'

# Install Operator Compliance Operator
# Deploys Operator --> Subscription and Operatorgroup
# Syncwave: 0
helper-operator:
  operators:
    elasticsearch-operator:
      enabled: false
      syncwave: '0'
      namespace:
        name: openshift-operators-redhat
        create: true
      subscription:
        approval: Automatic
        operatorName: elasticsearch-operator
        source: redhat-operators
        sourceNamespace: openshift-marketplace
      operatorgroup:
        notownnamespace: true
        create: true

    loki-operator:
      enabled: true
      syncwave: '0'
      namespace:
        name: openshift-operators-redhat
        create: true
      subscription:
        channel: stable-5.8
        approval: Automatic
        operatorName: loki-operator
        source: redhat-operators
        sourceNamespace: openshift-marketplace
      operatorgroup:
        # notownnamespace: true
        create: false

    cluster-logging-operator:
      enabled: true
      syncwave: '0'
      namespace:
        name: openshift-logging
        create: true
      subscription:
        approval: Automatic
        operatorName: cluster-logging
        source: redhat-operators
        sourceNamespace: openshift-marketplace
      operatorgroup:
        create: true

helper-status-checker:
  enabled: false

  checks:

    - operatorName: cluster-logging
      namespace:
        name: openshift-logging
      syncwave: 3

      serviceAccount:
        name: "status-checker-logging"

    - operatorName: loki-operator
      namespace:
        name: openshift-logging
      syncwave: 3

      serviceAccount:
        name: "status-checker-loki"
