---
# -- Enable Job to create a Secret for LokiStack.
# @default -- false
enabled: true

# -- Syncwave for Argo CD.
# @default -- 3
syncwave: '0'

# -- Namespace where LokiStack is deployed and where the Secret shall be created.
namespace: openshift-logging

# -- Name of Secret that shall be created.
secretname: logging-loki-s3-secret

# Bucket Configuration
bucket:
  # -- Name of the Bucket shall has been created.
  name: logging-loki-s3
