{{- with .Values.bucket }}
{{ if eq ( .enabled | toString) "true" }}
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
  labels:
    {{- include "common.labels" $ | nindent 4 }}
spec:
  generateBucketName: {{ .name }}
  storageClassName: {{ .storageclass | default "openshift-storage.noobaa.io" }}
{{- end }}
{{- end }}
