{{- with .Values.transformationAdvisorConfig }}
{{ if eq ( .enabled | toString) "true" }}
---
apiVersion: ta.ibm.com/v2
kind: TransAdv
metadata:
  name: ta
  labels:
    release: ibm-transformation-advisor-instance
    app.kubernetes.io/name: ibm-transformation-advisor
    app.kubernetes.io/instance: ibm-transformation-advisor-instance
    app.kubernetes.io/managed-by: ibm-transformation-advisor-manager
  namespace: ta-project
spec:
  networkPolicy:
    egress:
      default:
        - to:
            dnsName: github.com
          type: Allow
        - to:
            dnsName: github.ibm.com
          type: Allow
        - type: Allow
        - type: Allow
        - to:
            dnsName: {{ .cluster.dnsName }}
          type: Allow
      enabled: false
    enabled: true
  license:
    aLicenseType: {{ .aLicenseType }}
    accept: true
  route:
    rateLimit:
      enabled: true
      rateHttp: '200'
      rateTcp: '200'
    enabled: true
    hostname: {{ .cluster.hostname }}
  commonServices:
    cloudpakName: __TA_PLACEHOLDER_CLOUDPAK_NAME__
    cloudpakId: __TA_PLACEHOLDER_CLOUDPAK_ID__
    cloudpakVersion: __TA_PLACEHOLDER_CLOUDPAK_VERSION__
  transadv:
    security:
      cipherSuites: ''
    resources:
      limits:
        memory: 8Gi
        cpu: 16000m
        ephemeral-storage: 20Gi
      requests:
        memory: 1Gi
        cpu: 500m
        ephemeral-storage: 3Gi
    readinessProbe:
      timeoutSeconds: 30
      periodSeconds: 5
      failureThreshold: 15
    livenessProbe:
      initialDelaySeconds: 120
      timeoutSeconds: 30
      periodSeconds: 5
      failureThreshold: 15
    startupProbe:
      failureThreshold: 6
      periodSeconds: 10
    publicUrl: {{ .cluster.publicUrl }}
    logLevel: info
  couchdb:
    livenessProbe:
      initialDelaySeconds: 60
      timeoutSeconds: 3
      periodSeconds: 5
      failureThreshold: 6
    readinessProbe:
      initialDelaySeconds: 5
      timeoutSeconds: 3
      periodSeconds: 5
      failureThreshold: 6
    resources:
      limits:
        memory: 20Gi
        cpu: 16000m
        ephemeral-storage: 20Gi
      requests:
        memory: 1Gi
        cpu: 500m
        ephemeral-storage: 1Gi
    security:
      cipherSuites: ''
      tlsVersions: ''
  neo4j:
    livenessProbe:
      initialDelaySeconds: 60
      timeoutSeconds: 3
      periodSeconds: 5
      failureThreshold: 6
    readinessProbe:
      initialDelaySeconds: 5
      timeoutSeconds: 3
      periodSeconds: 5
      failureThreshold: 6
    resources:
      limits:
        memory: 8Gi
        cpu: 16000m
        ephemeral-storage: 5Gi
      requests:
        memory: 1Gi
        cpu: 500m
        ephemeral-storage: 1Gi
    logLevel: info
  custom:
    titleText: ''
    landingIcon: ''
    landingIcon2: ''
    landingIcon3: ''
    landingIcon4: ''
  authentication:
    disabled:
      liberty: false
      ui: false
    ocp:
      authIssuerEndpoint: {{ .cluster.authIssuerEndpoint }}
      apiEndpoint: {{ .cluster.apiEndpoint }}
      secretName: transformation-advisor-secret
    thirdParty:
      description: 'If the Third Party Authentication is not configured, will default to use OCP OAuthClient.'
  tls:
    enabled: true
    caCert: |
      ""
  transadvui:
    livenessProbe:
      initialDelaySeconds: 60
      timeoutSeconds: 5
      periodSeconds: 30
      failureThreshold: 15
    readinessProbe:
      initialDelaySeconds: 5
      timeoutSeconds: 5
      periodSeconds: 30
      failureThreshold: 15
    resources:
      limits:
        memory: 4Gi
        cpu: 16000m
        ephemeral-storage: 5Gi
      requests:
        memory: 1Gi
        cpu: 500m
        ephemeral-storage: 1Gi
    logLevel: info
    useSecureCookie: 'true'
  persistence:
    couchdb:
      supplementalGroups: []
      accessMode: ReadWriteOnce
      size: 20Gi
      useDynamicProvisioning: true
      existingClaim: ''
      storageClassName: {{ .storageClass }}
    neo4j:
      supplementalGroups: []
      accessMode: ReadWriteOnce
      size: 5Gi
      useDynamicProvisioning: true
      existingClaim: ''
      storageClassName: {{ .storageClass }}
    enabled: true
{{- end }}
{{- end }}
