apiVersion: v2
name: helper-lokistack
description: The only purpose of this helper chart is to provide a template for the LokiStack Custom Resource, so it must not be re-defined for multiple services.
version: 1.0.1
home: https://github.com/tjungbauer/helm-charts/tree/main/charts/helper-lokistack
icon: https://github.com/tjungbauer/helm-charts/raw/gh-pages/images/loki.png
dependencies:
  - name: helper-objectstore
    version: ~1.0.4
    repository: https://charts.stderr.at/
  - name: helper-loki-bucket-secret
    version: ~1.0.6
    repository: https://charts.stderr.at/
maintainers:
  - name: tjungbauer
    email: tjungbau@redhat.com
    url: https://blog.stderr.at/
sources:
  - https://github.com/tjungbauer/helm-charts
  - https://charts.stderr.at/
  - https://github.com/tjungbauer/openshift-clusterconfig-gitops
keywords:
  - helper
  - subchart
  - gitops
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/signKey: |
    fingerprint: B677CB52F8358FA091044E375D24D6846DBA8F8A
    url: https://keys.openpgp.org/vks/v1/by-fingerprint/B677CB52F8358FA091044E375D24D6846DBA8F8A
  artifacthub.io/changes: |
    - kind: added
      description: initial release
