apiVersion: v2
name: openshift-machineset
description: Deploy openshift-machineset
version: 1.0.28
home: https://github.com/luisbazo/helm-charts/tree/main/charts/openshift-machineset
#icon: https://raw.githubusercontent.com/tjungbauer/helm-charts/gh-pages/images/logging.svg
maintainers:
  - name: luisbazo
    email: luis.bazo@gmail.com
    url: https://github.com/luis/helm-charts
sources:
  - https://github.com/tjungbauer/helm-charts
  - https://charts.stderr.at/
  - https://github.com/luisbazo/helm-charts
keywords:
  - machineset
annotations:
  #artifacthub.io/license: Apache-2.0
  #artifacthub.io/signKey: |
    #fingerprint: B677CB52F8358FA091044E375D24D6846DBA8F8A
    #url: https://keys.openpgp.org/vks/v1/by-fingerprint/B677CB52F8358FA091044E375D24D6846DBA8F8A
  #artifacthub.io/changes: |
    #- kind: fixed
    #  description: Signing Chart
    #- kind: added
    #  description: Optimizing Loki configuration for ClusterLogging object.
    #- kind: added
    #  description: updated to helper-status-checker 4.0.0
