---
machineset:
  prefix: ocpinstall-xld2s
  role: infra
  enabled: true
  replicas: 3
  storage_machineset: true
  vsphere:
    numCoresPerSocket: 2
    diskGiB: 120
    userDataSecret: worker-user-data
    credentialsSecret: vsphere-cloud-credentials
    networkName: gym-6630026hom-pohx5w5d-segment
    numCPUs: 10
    datacenter: IBMCloud
    datastore: '/IBMCloud/datastore/gym-6630026hom-p6qlefk7-storage'
    folder: '/IBMCloud/vm/ocp-gym/gym-6630026hom-p6qlefk7'
    resourcePool: '/IBMCloud/host/ocp-gym/Resources/Cluster Resource Pool/Gym Member Resource Pool/gym-6630026hom-p6qlefk7'
    server: ocpgym-vc.techzone.ibm.local
    memoryMiB: 26624
