---
machineset:
  prefix: ocpinstall-9tfj4
  role: infra
  enabled: true
  replicas: 3
  storage_machineset: true
  vsphere:
    numCoresPerSocket: 2
    diskGiB: 120
    userDataSecret: worker-user-data
    credentialsSecret: vsphere-cloud-credentials
    networkName: gym-6630026hom-pohx5w5d-segment
    numCPUs: 10
    datacenter: IBMCloud
    datastore: '/IBMCloud/datastore/gym-6630026hom-pohx5w5d-storage'
    folder: '/IBMCloud/vm/ocpgym-wdc/gym-6630026hom-pohx5w5d'
    resourcePool: '/IBMCloud/host/ocpgym-wdc/Resources/Cluster Resource Pool/Gym Member Resource Pool/gym-6630026hom-pohx5w5d'
    server: ocpgymwdc-vc.techzone.ibm.local
    memoryMiB: 26624
