---
apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  name: {{ .Values.machineset.prefix }}-{{ .Values.machineset.role }}-0
  namespace: openshift-machine-api
  labels:
    machine.openshift.io/cluster-api-cluster: {{ .Values.machineset.prefix }}
spec:
  replicas: {{ .Values.machineset.replicas }}
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: {{ .Values.machineset.prefix }}
      machine.openshift.io/cluster-api-machineset: {{ .Values.machineset.prefix }}-{{ .Values.machineset.role }}-0
  template:
    metadata:
      labels:
        machine.openshift.io/cluster-api-cluster: {{ .Values.machineset.prefix }}
        machine.openshift.io/cluster-api-machine-role: {{ .Values.machineset.role }}
        machine.openshift.io/cluster-api-machine-type: {{ .Values.machineset.role }}
        machine.openshift.io/cluster-api-machineset: {{ .Values.machineset.prefix }}-{{ .Values.machineset.role }}-0
    spec:
      lifecycleHooks: {}
      metadata:
        labels:
          {{- if eq ( .Values.machineset.storage_machineset | toString) "true" }}
          cluster.ocs.openshift.io/openshift-storage: ''
          {{- end }}    
      providerSpec:
        value:
          numCoresPerSocket: {{ .Values.machineset.vsphere.numCoresPerSocket }}
          diskGiB: {{ .Values.machineset.vsphere.diskGiB }}
          snapshot: ''
          userDataSecret:
            name: {{ .Values.machineset.vsphere.userDataSecret }}
          memoryMiB: {{ .Values.machineset.vsphere.memoryMiB }}
          credentialsSecret:
            name: {{ .Values.machineset.vsphere.credentialsSecret }}
          network:
            devices:
              - networkName: {{ .Values.machineset.vsphere.networkName }}
          metadata:
            creationTimestamp: null
          numCPUs: {{ .Values.machineset.vsphere.numCPUs }}
          kind: VSphereMachineProviderSpec
          workspace:
            datacenter: {{ .Values.machineset.vsphere.datacenter }}
            datastore: {{ .Values.machineset.vsphere.datastore }}
            folder: {{ .Values.machineset.vsphere.folder }}
            resourcePool: {{ .Values.machineset.vsphere.resourcePool }}
            server: {{ .Values.machineset.vsphere.server }}
          template: {{ .Values.machineset.prefix }}-rhcos-generated-region-generated-zone
          apiVersion: machine.openshift.io/v1beta1
