apiVersion: v2
name: openshift-data-foundation
description: Deploys and configures the OpenShift Data Foundation Operator.
version: 1.0.29
home: https://github.com/luisbazo/helm-charts/tree/main/charts/openshift-data-foundation
dependencies:
  - name: helper-operator
    version: ~1.0.14
    repository: https://charts.stderr.at/
  - name: helper-status-checker
    version: ~4.0.0
    repository: https://charts.stderr.at/
    condition: helper-status-checker.enabled
maintainers:
  - name: tjungbauer
    email: tjungbau@redhat.com
    url: https://blog.stderr.at/
sources:
  - https://github.com/tjungbauer/helm-charts
  - https://charts.stderr.at/
  - https://github.com/tjungbauer/openshift-clusterconfig-gitops
keywords:
  - storage
  - odf
