apiVersion: v2
name: prometheus-example-app
description: This is a prometheus example application to expose metrics. It's created a prometheus alert to trigger an alarm and it is also created a platform alert on workers above 70% CPU consumption as an example
version: 1.0.23
home: https://github.com/luisbazo/helm-charts/tree/main/charts/prometheus-example-app
maintainers:
  - name: luisbazo
    email: luis.bazo@gmail.com
    url: https://blog.stderr.at/
sources:
  - https://github.com/tjungbauer/helm-charts
  - https://charts.stderr.at/
  - https://github.com/tjungbauer/openshift-clusterconfig-gitops
keywords:
  - promotheus-example-app
