{{- if eq ( .Values.enabled | toString) "true" }}
{{- with .Values }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: create-loki-secret-sa
  annotations:
    argocd.argoproj.io/sync-wave: {{ .syncwave | default "3" | quote }}
  namespace: {{ .namespace }}
{{- end }}
{{- end }}
