{{- if eq ( .Values.enabled | toString) "true" }}
{{- with .Values }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: create-loki-secret-crb-{{ .namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ .syncwave | default "3" | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
  - kind: ServiceAccount
    name: create-loki-secret-sa
    namespace: {{ .namespace }}
{{- end }}
{{- end }}
