{{- if eq ( .Values.enabled | toString) "true" }}
{{- with .Values }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: create-loki-secret-sa
  namespace: {{ .namespace }}
{{- end }}
{{- end }}
